export const dataSources = [
  { id: 'lastfm', name: '音楽 (Last.fm)', category: '音楽', icon: '♫', phase: 'mvp', color: '#00F0FF' },
  { id: 'strava', name: '運動 (Strava)', category: '運動', icon: '🚴', phase: 'phase2', color: '#FF3366' },
  { id: 'oura', name: '睡眠 (Oura)', category: '睡眠', icon: '😴', phase: 'phase2', color: '#BD93F9' },
  { id: 'intervals', name: 'フィットネス (intervals.icu)', category: 'フィットネス', icon: '💪', phase: 'phase2', color: '#50FA7B' },
  { id: 'instagram', name: 'Instagram', category: 'SNS', icon: '📸', phase: 'phase2', color: '#FF9500' },
  { id: 'twitter', name: 'Twitter', category: 'SNS', icon: '🐦', phase: 'phase2', color: '#1DA1F2' },
  { id: 'gcal_holiday', name: '休日予定 (Google Calendar)', category: '予定', icon: '🏖️', phase: 'phase2', color: '#FFB86C' },
  { id: 'gcal_live', name: 'ライブ (Google Calendar)', category: 'ライブ', icon: '🎵', phase: 'phase2', color: '#FF79C6' },
  { id: 'gmail', name: '買い物 (Gmail)', category: '買い物', icon: '🛒', phase: 'phase2', color: '#8BE9FD' },
  { id: 'kashidashi', name: '図書館 (kashidashi)', category: '読書', icon: '📚', phase: 'phase2', color: '#ADFF2F' },
  { id: 'bookmeter', name: '読書メーター', category: '読書', icon: '📖', phase: 'phase3', color: '#ADFF2F' },
  { id: 'filmarks', name: '映画 (Filmarks)', category: '映画', icon: '🎬', phase: 'phase3', color: '#FF9500' },
  { id: 'github', name: 'GitHub', category: 'コーディング', icon: '💻', phase: 'phase3', color: '#50FA7B' },
  { id: 'claude', name: 'Claude Code', category: 'コーディング', icon: '🤖', phase: 'phase3', color: '#D4A574' },
  { id: 'openai', name: 'OpenAI', category: 'コーディング', icon: '🧠', phase: 'phase3', color: '#74AA9C' },
  { id: 'bathmat', name: '体重 (Smart Bath Mat)', category: '体重', icon: '⚖️', phase: 'phase3', color: '#F8F8F2' },
  { id: 'spotify_pod', name: 'Podcasts (Spotify)', category: '音楽', icon: '🎧', phase: 'phase3', color: '#1DB954' },
]
